### ISSUE TITLE
不支持PHP吗？

### ISSUE THREAD

**Issue by 54853315** [JacksonTian/doxmate#35]
➜  ***** git:(master) ✗ cd Application 
➜  Application git:(master) ✗ doxmate build
{ [Error: Command failed: 
module.js:340
    throw err;
          ^
Error: Cannot find module '/Applications/XAMPP/xamppfiles/htdocs/******/Application/package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.exports.process (/usr/local/lib/node_modules/doxmate/lib/doxmate.js:164:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/doxmate/bin/doxmate-build:36:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
] killed: false, code: 8, signal: null }

**Comment by DevinXian** [comment]
这个是基于![dox](https://github.com/tj/dox)使用node方式实现的，用于javascript文档生成，php的话，可以尝试自己写一个咯～package.json是node包管理工具的清单文件，php应该是没有的～

**Comment by JacksonTian** [comment]
嗯。不支持php
